version: '3.0'

services: 
  coffeeapp:
    image: oriankeith/coffeeapp
    build:
      context: .
    depends_on:
      - db
  db:
    image: keinos/sqlite3:latest
    volumes:
      - ./:/workspace
    working_dir: /workspace
    stdin_open: true
    tty: true

